[urls]

  [urls.marks_for_period]
  url = "https://dnevnik2.petersburgedu.ru/api/journal/estimate/table"

    [urls.marks_for_period.params]
    'p_educations[]' = 204383
    p_date_from = "02.09.2021"
    p_date_to = "29.09.2021"
    p_limit = 200
    p_page = 1